---
abstract: 'Installs all of the modules in the POE::* namespace'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
configure_requires:
  CPANPLUS: 0.90
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-POE-All
provides:
  Task::POE::All:
    file: lib/Task/POE/All.pm
    version: 1.02
requires:
  POE::API::Hooks: 2.03
  POE::API::Peek: 2.15
  POE::Component::AI::MegaHAL: 1.18
  POE::Component::AIO: 1.00
  POE::Component::Algorithm::Evolutionary: 0.002001
  POE::Component::Amazon::S3: 0.01
  POE::Component::App::PNGCrush: 0.001
  POE::Component::Archive::Any: 0.001
  POE::Component::AssaultCube::ServerQuery::Server: 0.04
  POE::Component::AtomAggregator: 1.0
  POE::Component::Audio::Mad::Dispatch: 0.3
  POE::Component::Basement: 0.01
  POE::Component::BlogCloud: 0.01
  POE::Component::CD::Detect: 1.1
  POE::Component::CD::Rip: 1.2
  POE::Component::CPAN::LinksToDocs::No404s: 0.001
  POE::Component::CPAN::LinksToDocs::No404s::Remember: 0.002
  POE::Component::CPAN::Mirror::Multiplexer: 0.04
  POE::Component::CPAN::Reporter: 0.06
  POE::Component::CPAN::SQLite::Info: 0.08
  POE::Component::CPAN::YACSmoke: 1.36
  POE::Component::CPANIDX: 0.04
  POE::Component::CPANPLUS::YACSmoke: 1.62
  POE::Component::CSS::Minifier: 0.0101
  POE::Component::Cache: 0.001001
  POE::Component::Captcha::reCAPTCHA: 0.02
  POE::Component::Child: 1.39
  POE::Component::Client::AMQP::Channel: 0.01
  POE::Component::Client::AirTunes: 0.01
  POE::Component::Client::Asterisk::Manager: 0.08
  POE::Component::Client::CouchDB::Database: 0.05
  POE::Component::Client::DNS: 1.051
  POE::Component::Client::DNS::Recursive: 1.00
  POE::Component::Client::DNSBL: 1.02
  POE::Component::Client::FTP: 0.22
  POE::Component::Client::HTTPDeferred: 0.02
  POE::Component::Client::Halo: 0.2
  POE::Component::Client::Icecast: 0.12
  POE::Component::Client::Ident::Agent: 1.16
  POE::Component::Client::Keepalive: 0.262
  POE::Component::Client::Lingr: 0.04
  POE::Component::Client::MPD::Types: 1.100430
  POE::Component::Client::MSN: 0.03
  POE::Component::Client::MogileFS: 0.02
  POE::Component::Client::NNTP: 2.16
  POE::Component::Client::NNTP::Tail: 0.01
  POE::Component::Client::NRPE: 0.16
  POE::Component::Client::NSCA: 0.16
  POE::Component::Client::NTP: 0.02
  POE::Component::Client::POP3: 0.02
  POE::Component::Client::Pastebot: 1.12
  POE::Component::Client::Ping: 1.163
  POE::Component::Client::RADIUS: 1.02
  POE::Component::Client::Rcon: 0.23
  POE::Component::Client::SMTP: 0.22
  POE::Component::Client::SOAP: 0.01
  POE::Component::Client::SOCKS: 1.00
  POE::Component::Client::Stomp: 0.10
  POE::Component::Client::Stomp::Utils: 0.01
  POE::Component::Client::TCPMulti: 0.0521
  POE::Component::Client::Telnet: 0.06
  POE::Component::Client::Traceroute: 0.21
  POE::Component::Client::Twitter: 0.01
  POE::Component::Client::UserAgent: 0.08
  POE::Component::Client::Whois::IPBlks: 1.28
  POE::Component::Client::Whois::Smart: 0.187
  POE::Component::Client::opentick: 0.21
  POE::Component::ControlPort: 1.0266
  POE::Component::Cron: 0.021
  POE::Component::Curses: 0.100680
  POE::Component::DBIAgent: 0.26
  POE::Component::DHCP::Monitor: 1.02
  POE::Component::Daemon::Scoreboard: 0.1100
  POE::Component::Daemon::Win32: 0.01
  POE::Component::Data::SimplePassword: 0.0101
  POE::Component::DebugShell: 1.412
  POE::Component::DebugShell::Jabber: 0.04
  POE::Component::DirWatch: 0.200000
  POE::Component::DirWatch::Object: 0.10
  POE::Component::Drizzle: 0.02
  POE::Component::EasyDBI: 1.23
  POE::Component::Enc::Flac: 1.01
  POE::Component::Enc::Mp3: 1.2
  POE::Component::Enc::Ogg: 1.05
  POE::Component::FastCGI: 0.1
  POE::Component::Fuse::SubProcess: 0.05
  POE::Component::GCS::Server: 0.03
  POE::Component::Gearman::Client: 0.03
  POE::Component::Generic::Net::SSH2: 0.1205
  POE::Component::Github::Request::Role: 0.06
  POE::Component::Growl: 1.00
  POE::Component::Hailo: 0.09
  POE::Component::IKC::Proxy: 0.2200
  POE::Component::IRC::Object: 0.02
  POE::Component::IRC::Plugin::AlarmClock: 0.001
  POE::Component::IRC::Plugin::AntiSpamMailTo: 0.0101
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.006
  POE::Component::IRC::Plugin::BaseWrap: 0.009
  POE::Component::IRC::Plugin::Blowfish: 0.01
  POE::Component::IRC::Plugin::Bollocks: 1.00
  POE::Component::IRC::Plugin::BrowserSupport: 0.002
  POE::Component::IRC::Plugin::CPAN::Info: 0.03
  POE::Component::IRC::Plugin::CPAN::LinksToDocs: 0.001
  POE::Component::IRC::Plugin::CPAN::LinksToDocs::No404s: 0.002
  POE::Component::IRC::Plugin::CPAN::LinksToDocs::No404s::Remember: 0.001
  POE::Component::IRC::Plugin::CSS::Minifier: 0.0101
  POE::Component::IRC::Plugin::CSS::PropertyInfo: 0.002
  POE::Component::IRC::Plugin::CSS::SelectorTools: 0.001
  POE::Component::IRC::Plugin::CoinFlip: 0.0102
  POE::Component::IRC::Plugin::CoreList: 1.00
  POE::Component::IRC::Plugin::Data::SimplePassword: 0.0101
  POE::Component::IRC::Plugin::FTP::EasyUpload: 0.001
  POE::Component::IRC::Plugin::Fortune: 0.0101
  POE::Component::IRC::Plugin::Google::Calculator: 0.03
  POE::Component::IRC::Plugin::Google::PageRank: 0.01
  POE::Component::IRC::Plugin::HTML::AttributeInfo: 0.002
  POE::Component::IRC::Plugin::HTML::ElementInfo: 0.001
  POE::Component::IRC::Plugin::Hailo: 0.10
  POE::Component::IRC::Plugin::ImageMirror: 0.06
  POE::Component::IRC::Plugin::JavaScript::Minifier: 0.0101
  POE::Component::IRC::Plugin::Magic8Ball: 0.0101
  POE::Component::IRC::Plugin::MegaHAL: 0.38
  POE::Component::IRC::Plugin::OutputToPastebin: 0.001
  POE::Component::IRC::Plugin::PAUSE::RecentUploads: 0.05
  POE::Component::IRC::Plugin::POE::Knee: 1.08
  POE::Component::IRC::Plugin::Proxy: 6.28
  POE::Component::IRC::Plugin::QueryDNS: 1.00
  POE::Component::IRC::Plugin::QueryDNSBL: 1.00
  POE::Component::IRC::Plugin::RSS::Headlines: 1.08
  POE::Component::IRC::Plugin::RTorrentStatus: 0.03
  POE::Component::IRC::Plugin::Role: 0.06
  POE::Component::IRC::Plugin::SigFail: 0.001
  POE::Component::IRC::Plugin::Syntax::Highlight::CSS: 0.0101
  POE::Component::IRC::Plugin::Syntax::Highlight::HTML: 0.0101
  POE::Component::IRC::Plugin::Thanks: 0.02
  POE::Component::IRC::Plugin::Trac::RSS: 0.11
  POE::Component::IRC::Plugin::URI::Find: 1.08
  POE::Component::IRC::Plugin::Unicode::UCD: 0.001
  POE::Component::IRC::Plugin::Validator::CSS: 0.02
  POE::Component::IRC::Plugin::Validator::HTML: 0.002
  POE::Component::IRC::Plugin::WWW::Alexa::TrafficRank: 0.0101
  POE::Component::IRC::Plugin::WWW::CPAN: 0.0101
  POE::Component::IRC::Plugin::WWW::CPANRatings::RSS: 0.0103
  POE::Component::IRC::Plugin::WWW::Cache::Google: 0.0101
  POE::Component::IRC::Plugin::WWW::DoctypeGrabber: 0.0101
  POE::Component::IRC::Plugin::WWW::GetPageTitle: 0.0102
  POE::Component::IRC::Plugin::WWW::Google::Time: 0.0101
  POE::Component::IRC::Plugin::WWW::HTMLTagAttributeCounter: 0.0101
  POE::Component::IRC::Plugin::WWW::LimerickDB: 0.0102
  POE::Component::IRC::Plugin::WWW::Lipsum: 0.0103
  POE::Component::IRC::Plugin::WWW::OhNoRobotCom::Search: 0.001
  POE::Component::IRC::Plugin::WWW::XKCD::AsText: 0.002
  POE::Component::IRC::Plugin::YouAreDoingItWrong: 0.02
  POE::Component::IRC::Plugin::YouTube::MovieFindStore: 0.02
  POE::Component::Jabber::Protocol: 3.00
  POE::Component::JavaScript::Minifier: 0.0101
  POE::Component::JobQueue: 0.570
  POE::Component::LaDBI: 1.002001
  POE::Component::Lightspeed: 0.05
  POE::Component::Lingua::Translate: 0.05
  POE::Component::Log4perl: 0.03
  POE::Component::Logger: 1.00
  POE::Component::MDBA: 0.01003
  POE::Component::MXML: 0.03
  POE::Component::MessageQueue: 0.002008
  POE::Component::Metabase::Client::Submit: 0.06
  POE::Component::Metabase::Relay::Server: 0.06
  POE::Component::Net::FTP: 0.001
  POE::Component::Net::LastFM::Submission: 0.24
  POE::Component::NomadJukebox: 0.02
  POE::Component::NonBlockingWrapper::Base: 0.002
  POE::Component::OSCAR: 0.05
  POE::Component::Omegle: 0.02
  POE::Component::OpenSSH: 0.06
  POE::Component::PSD::Client: 0.01
  POE::Component::Pcap: 0.04
  POE::Component::Player::Mpg123: 1.2
  POE::Component::Player::Musicus: 1.32
  POE::Component::Player::Slideshow: 1.4
  POE::Component::Player::Xmms: 0.04
  POE::Component::Pluggable::Constants: 1.24
  POE::Component::PluginManager: 0.67
  POE::Component::Pool::DBI: 0.014
  POE::Component::Pool::Thread: 0.015
  POE::Component::PreforkDispatch: 0.101
  POE::Component::Proxy::SOCKS: 1.02
  POE::Component::Proxy::TCP: 1.2
  POE::Component::Q4M: 0.00002
  POE::Component::RSS: 3.01
  POE::Component::RSSAggregator: 1.11
  POE::Component::RemoteTail: 0.01011
  POE::Component::Rendezvous::Publish: 0.01
  POE::Component::ResourcePool: 0.04
  POE::Component::ResourcePool::Resource::TokenBucket: 0.01
  POE::Component::SASLAuthd: 0.01
  POE::Component::SNMP: 1.1006
  POE::Component::SNMP::Session: 0.1202
  POE::Component::SSLify::ClientHandle: 0.18
  POE::Component::Schedule: 0.94
  POE::Component::Server::Bayeux: 0.04
  POE::Component::Server::BigBrother: 0.07
  POE::Component::Server::Chargen: 1.14
  POE::Component::Server::DNS: 0.20
  POE::Component::Server::Daytime: 1.14
  POE::Component::Server::Discard: 1.14
  POE::Component::Server::Echo: 1.64
  POE::Component::Server::FTP: 0.08
  POE::Component::Server::HTTP: 0.09
  POE::Component::Server::HTTP::KeepAlive: 0.0302
  POE::Component::Server::HTTPServer: 0.009002
  POE::Component::Server::IRC::Pipeline: 1.40
  POE::Component::Server::Ident: 1.16
  POE::Component::Server::Inet: 0.04
  POE::Component::Server::JSONRPC: 0.02
  POE::Component::Server::NNTP: 1.04
  POE::Component::Server::NRPE: 0.16
  POE::Component::Server::NSCA: 0.08
  POE::Component::Server::POP3: 0.08
  POE::Component::Server::PSGI: 0.5
  POE::Component::Server::Postfix::TCP: 0.001
  POE::Component::Server::PreforkTCP: 0.11
  POE::Component::Server::Qotd: 1.14
  POE::Component::Server::RADIUS: 1.02
  POE::Component::Server::SOAP: 1.14
  POE::Component::Server::SimpleContent: 1.14
  POE::Component::Server::SimpleHTTP::Connection: 2.0
  POE::Component::Server::SimpleSMTP: 1.44
  POE::Component::Server::SimpleXMLRPC: 0.02
  POE::Component::Server::Syslog: 1.18
  POE::Component::Server::Time: 1.14
  POE::Component::Server::Twirc: 0.10
  POE::Component::Server::XMLRPC: 0.05
  POE::Component::SimpleDBI::SubProcess: 1.29
  POE::Component::SimpleLog: 1.05
  POE::Component::SmokeBox::Backend::Test::SmokeBox::Mini: 0.26
  POE::Component::SmokeBox::Dists: 1.00
  POE::Component::SmokeBox::Recent::FTP: 1.18
  POE::Component::SmokeBox::Result: 0.36
  POE::Component::SmokeBox::Uploads::CPAN::Mini: 1.00
  POE::Component::SmokeBox::Uploads::NNTP: 1.00
  POE::Component::SmokeBox::Uploads::RSS: 1.00
  POE::Component::SmokeBox::Uploads::Rsync: 0.03
  POE::Component::StackedProcessor: 0.05
  POE::Component::SubWrapper: 2.01
  POE::Component::Supervisor: 0.05
  POE::Component::Syntax::Highlight::CSS: 0.0202
  POE::Component::Syntax::Highlight::HTML: 0.0201
  POE::Component::TFTPd: 0.03
  POE::Component::TSTP: 0.02
  POE::Component::Telephony::CTPort: 0.03
  POE::Component::Tie: 0.01
  POE::Component::UserBase: 0.09
  POE::Component::WWW::Alexa::TrafficRank: 0.001
  POE::Component::WWW::CPAN: 0.0101
  POE::Component::WWW::CPANRatings::RSS: 0.0101
  POE::Component::WWW::Cache::Google: 0.0201
  POE::Component::WWW::DoctypeGrabber: 0.0102
  POE::Component::WWW::DoingItWrongCom::RandImage: 0.02
  POE::Component::WWW::GetPageTitle: 0.0101
  POE::Component::WWW::Google::Calculator: 0.02
  POE::Component::WWW::Google::PageRank: 0.04
  POE::Component::WWW::Google::Time: 0.0101
  POE::Component::WWW::HTMLTagAttributeCounter: 0.0101
  POE::Component::WWW::LimerickDB: 0.0103
  POE::Component::WWW::Lipsum: 0.0102
  POE::Component::WWW::OhNoRobotCom::Search: 0.001
  POE::Component::WWW::PAUSE::CleanUpHomeDir: 0.0101
  POE::Component::WWW::PAUSE::RecentUploads: 0.06
  POE::Component::WWW::PAUSE::RecentUploads::Tail: 0.05
  POE::Component::WWW::Pastebin::Bot::Pastebot::Create: 0.002
  POE::Component::WWW::Pastebin::Many::Retrieve: 0.001
  POE::Component::WWW::Search::Mininova: 0.04
  POE::Component::WWW::Shorten: 1.18
  POE::Component::WWW::WebDevout::BrowserSupportInfo: 0.01
  POE::Component::WWW::XKCD::AsText: 0.001
  POE::Component::WWW::YouTube::VideoURI: 0.06
  POE::Component::WakeOnLAN: 1.02
  POE::Component::WebService::HtmlKitCom::FavIconFromImage: 0.002
  POE::Component::WebService::Validator::CSS::W3C: 0.02
  POE::Component::WebService::Validator::HTML::W3C: 0.07
  POE::Component::Win32::ChangeNotify: 1.20
  POE::Component::Win32::EventLog: 1.24
  POE::Component::Win32::Service: 1.24
  POE::Component::XUL: 0.02
  POE::Component::YahooMessenger: 0.05
  POE::Component::YubiAuth: 0.04
  POE::Declarative: 0.08
  POE::Declare::Meta::Attribute: 0.22
  POE::Devel::Benchmarker::GetInstalledLoops: 0.05
  POE::Devel::ProcAlike::POEInfo: 0.02
  POE::Devel::Profiler: 0.02
  POE::Driver::Spread: 0.01
  POE::Driver::SpreadClient: 0.08
  POE::Event::Message: 0.11
  POE::Filter::ASN1: 0.01
  POE::Filter::BigBrother: 0.13
  POE::Filter::Bzip2: 1.58
  POE::Filter::CSV: 1.16
  POE::Filter::CSV_XS: 1.16
  POE::Filter::DHCPd::Lease: 0.04
  POE::Filter::ErrorProof: 0.01
  POE::Filter::FSSocket: 0.07
  POE::Filter::Finger: 0.08
  POE::Filter::HTTP::Parser: 1.02
  POE::Filter::HTTPD::Chunked: 0.9
  POE::Filter::HTTPHead: 0.895
  POE::Filter::Hessian: 1.00
  POE::Filter::IASLog: 1.08
  POE::Filter::IRC::Hybrid: 0.996
  POE::Filter::IRCD: 2.42
  POE::Filter::JSON: 0.04
  POE::Filter::JSON::Incr: 0.03
  POE::Filter::KennySpeak: 1.00
  POE::Filter::LOLCAT: 1.10
  POE::Filter::LZF: 1.70
  POE::Filter::LZO: 1.70
  POE::Filter::LZW: 1.72
  POE::Filter::LZW::Progressive: 0.1
  POE::Filter::Log::IPTables: 0.02
  POE::Filter::Log::Procmail: 0.03
  POE::Filter::Ls: 0.01
  POE::Filter::PPPHDLC: 0.01
  POE::Filter::ParseWords: 1.06
  POE::Filter::Postfix::Base64: 0.003
  POE::Filter::RecDescent: 0.02
  POE::Filter::RecordBlock: 1.289
  POE::Filter::Regexp: 1.0
  POE::Filter::SMTP: 1.2
  POE::Filter::SimpleHTTP::Error: 0.091710
  POE::Filter::Slim::CLI: 0.02
  POE::Filter::Snort: 0.031
  POE::Filter::Stomp: 0.03
  POE::Filter::TacacsPlus: 1.06
  POE::Filter::Transparent::SMTP: 0.2
  POE::Filter::XML::Node: 0.38
  POE::Filter::XML::RPC::Request: 0.04
  POE::Filter::Zlib: 2.02
  POE::Framework::MIDI: 0.09
  POE::Loop::EV: 0.06
  POE::Loop::Event: 1.304
  POE::Loop::Glib: 0.038
  POE::Loop::Gtk: 1.305
  POE::Loop::Kqueue: 0.02
  POE::Loop::Prima: 1.01
  POE::Loop::Tk: 1.304
  POE::Loop::Wx: 0.04
  POE::Session::Attribute: 0.80
  POE::Session::AttributeBased: 0.10
  POE::Session::Cascading: 2.01
  POE::Session::GladeXML2: 0.40
  POE::Session::Irssi: 0.50
  POE::Session::MessageBased: 0.111
  POE::Session::MultiDispatch: 1.3
  POE::Session::Multiplex: 0.0403
  POE::Session::PlainCall: 0.0201
  POE::Session::YieldCC: 0.202
  POE::Stage: 0.060
  POE::Sugar::Args: 1.3
  POE::TIKC: 0.02
  POE::Test::Helpers: 0.06
  POE::Test::Loops: 1.035
  POE::Wheel::GnuPG: 0.01
  POE::Wheel::Null: 0.01
  POE::Wheel::Run::Win32: 0.18
  POE::Wheel::UDP: 0.02
  POE::Wheel::VimColor: 0.0
  POE::XS::Loop::EPoll: 1.001
  POE::XS::Loop::Poll: 1.000
  POE::XS::Queue::Array: 0.006
  POE::XUL::Node: 0.05
  POE::strict: 3.01
  POEx::ProxySession::MessageSender: 0.092360
  POEx::PubSub::Event: 1.100910
  POEx::Role::SessionInstantiation::Meta::Session::Implementation: 1.100920
  POEx::Role::TCPClient: 1.100910
  POEx::Role::TCPServer: 1.100910
  POEx::Trait::DeferredRegistration: 0.092681
  POEx::Trait::ExtraInitialization: 0.092720
  POEx::Types: 1.100910
  POEx::URI: 0.0300
  POEx::WorkerPool: 1.100960
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 1.02
